[[library]]
name = "libSPIRV_Tools"
file = "libSPIRV-Tools"

[[library]]
name = "libSPIRV_Tools_diff"
file = "libSPIRV-Tools-diff"

[[library]]
name = "libSPIRV_Tools_link"
file = "libSPIRV-Tools-link"

[[library]]
name = "libSPIRV_Tools_lint"
file = "libSPIRV-Tools-lint"

[[library]]
name = "libSPIRV_Tools_opt"
file = "libSPIRV-Tools-opt"

[[binary]]
name = "spirv_as"
file = "spirv-as"

[[binary]]
name = "spirv_cfg"
file = "spirv-cfg"

[[binary]]
name = "spirv_dis"
file = "spirv-dis"

[[binary]]
name = "spirv_link"
file = "spirv-link"

[[binary]]
name = "spirv_lint"
file = "spirv-lint"

[[binary]]
name = "spirv_objdump"
file = "spirv-objdump"

[[binary]]
name = "spirv_opt"
file = "spirv-opt"

[[binary]]
name = "spirv_reduce"
file = "spirv-reduce"

[[binary]]
name = "spirv_val"
file = "spirv-val"
